### ISSUE TITLE
Use API gateway to enable notifications in lambda

### ISSUE THREAD

**Issue by wesselt** [wesselt/bunq2ynab#26]
https://aws.amazon.com/api-gateway/

**Comment by javydekoning** [comment]
@wesselt , I've added the API Gateway callback URL and it's now stored in SSM. However, I need your help registering this URL with Bunq, and making sure we don't do it on every invoke.

To deploy:
- Clone the config branch
- Remove `miniupnpc` from `requirements.txt` (sam build fails because of this package).
- Run `sam build`
- Run `sam deploy --guided`

**Comment by wesselt** [comment]
@javydekoning Cool!  I'll try to set up sam today and look at the callback tomorrow.

**Comment by wesselt** [comment]
Took some more time then expected!

- Found a way to create a separate `requirements_aws.txt` using a Makefile.  So miniupnpc can stay in the regular one, and boto3 can go in the AWS one.
- Had to use `sam build --use-container` or the Lamba gave an error about being unable to import `_cffi_backend`. Not sure why `--use-container` fixes that, just found it on the internet.
- `sam deploy` gave a "circular reference" error until I removed the parameters from `template.yaml`
- Removed the Cron event so it doesn't mess up tests, but it should be put back eventually

The callback works for me. When I make a payment between two accounts, it shows up immediately in YNAB, and I can see in the AWS log that the Lambda was invoked.

**Comment by javydekoning** [comment]
Awesome! I'll test and review today.

- '--use-container' fixes that because it's a binary dependency. If you build in a container it uses and amazon-linux container to build. Without it, it uses your local system and the binary is incompatible with the Lambda.
- You got a circular dependency because you tried to add then HttpApi (which is output from the ServerLessfunction) as a PARAM to de same resource. Making it dependend in itself. Hence, having it as ssm param fixes that.

**Comment by javydekoning** [comment]
Deployed the latest but it's not creating the callback...

```
2020-09-22 13:54:20,165 | INFO | lambda_function.py:13 | add_callbacks | SSM callback = ""
```

**Comment by wesselt** [comment]
That looks like the callback url isn’t set. What does the bunq2ynab-state parameter look like? It should contain the URL after deploying.

**Comment by javydekoning** [comment]
There is no Callback URL, just an emptystring... I see it was there after deployment, but has since been overwritten. 

![Screenshot 2020-09-22 at 16 37 42](https://user-images.githubusercontent.com/4455323/93897233-1e5e4080-fcf2-11ea-88f3-4f62552cdc66.png)

I think it's best if we move the API ID back to ENV variables to prevent this.

**Comment by wesselt** [comment]
It’s set from template.yaml:

`"aws_callback": "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/bunq2ynab-lambda"`

What happens if you delete the cloud formation stack before you run deploy?

Ah wait, I remember I had this problem too. An old version of state.py would initialize it to “”.

**Comment by javydekoning** [comment]
I was able to fix it, perhaps the deployment crossed with an already running sync. That said, I still think storing the callback url as an environment variable would be better. I don't see why it should be in the mutable state, as it should never change after deployment.

**Comment by wesselt** [comment]
From the code's point of view, it's easier to have fewer locations where information is stored. I made quite a few mistakes by combining environment, command line parameters, and config settings.
Right now the "config.json" is meant for the user to edit. The callback url is not configured by the end user, so I put it in the state, even though it is not mutable.
I've been running the current version for a week now and it seems stable. I think it's ready to move to master and the serverless template store.

**Comment by javydekoning** [comment]
Yes, I agree. The API Gateway integration is running excellent for me as well for the last couple of days. 

Let's merge to master and then work on smaller incremental improvements :). Thanks!

**Comment by wesselt** [comment]
I've updated the README for local usage. When you've updated the README for installation in AWS I'll merge the config branch to master.

**Comment by javydekoning** [comment]
I'll work on it tomorrow! :-)

**Comment by javydekoning** [comment]
@wesselt sorry for the delay, work completed and published to the Serverless Application Repository. Should be super easy to deploy now especially if names match between Bunq and Ynab :-) 👍

**Comment by wesselt** [comment]
Works like a charm once I figured out to click "Published applications"!  Merged to master. 👍
